# Generated by Django 3.1.4 on 2021-01-13 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210112_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 10, 5, 0, 429278)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=9, default=1.0, max_digits=25),
        ),
    ]
